server:
    port: ${PORT}

spring:
    application:
        name: Quick Mail

    web:
        resources:
            add-mappings: false

    mail:
        host: ${EMAIL_HOST}
        port: ${EMAIL_PORT}
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: ${SMTP_AUTH}
                    starttls:
                        enable: ${SMTP_STARTTLS_ENABLE}
                        required: ${SMTP_STARTTLS_REQUIRE}
                    ssl:
                        enable: ${SMTP_SSL_ENABLE}
                        trust: ${SMTP_SSL_TRUST}
                    connectiontimeout: ${SMTP_CONNECTIONTIMEOUT}
                    timeout: ${SMTP_TIMEOUT}
                    writetimeout: ${SMTP_WRITETIMEOUT}

email:
    from: ${EMAIL_USERNAME}

#Open api swagger ui 
springdoc: 
    api-docs: 
        path: /api-docs

#prefix endpoints configuration
api:
    prefix: ${PREFIX_APP}

logging:
  level:
    com.alness.quickmail: info
    org.springframework: info
  file:
    #   max-size: 50G
    name: logs/quickmail_app.log
    path: logs