server:
    port: ${PORT}

spring:
    application:
        name: Quick Mail

    web:
        resources:
            add-mappings: false

    #datasource
    datasource:
        url: jdbc:postgresql://${DB_URL}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa: 
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #hibernate: 
            #ddl-auto: create

    mail:
        host: ${EMAIL_HOST}
        port: ${EMAIL_PORT}
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: ${SMTP_AUTH}
                    starttls:
                        enable: ${SMTP_STARTTLS_ENABLE}
                        required: ${SMTP_STARTTLS_REQUIRE}
                    ssl:
                        enable: ${SMTP_SSL_ENABLE}
                        trust: ${SMTP_SSL_TRUST}
                    connectiontimeout: ${SMTP_CONNECTIONTIMEOUT}
                    timeout: ${SMTP_TIMEOUT}
                    writetimeout: ${SMTP_WRITETIMEOUT}

email:
    from: ${EMAIL_USERNAME}

#Open api swagger ui 
springdoc: 
    api-docs: 
        path: /api-docs

#prefix endpoints configuration
api:
    prefix: ${PREFIX_APP}

logging:
  level:
    com.alness.quickmail: info
    org.springframework: info
  file:
    #   max-size: 50G
    name: logs/quickmail_app.log
    path: logs


cron:
    expresion: ${CRON_EXPRESION}